# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreeProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200)),
                ('working', models.BooleanField(default=True)),
                ('number_of_uses', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
