# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeproxy',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
